# Categories that use hardcoded word:hint pairs
PAIRED_CATEGORIES = {
    "anime": {
        "naruto": "hokage",
        "goku": "saiyan",
        "luffy": "pirate",
        "ichigo": "soul reaper",
        "sasuke": "revenge",
        "vegeta": "prince",
        "eren": "future",
        "levi": "captain",
        "light yagami": "book",
        "hashirama": "wood",
        "minato": "teleport",
        "alphonse elric": "armour",
        "spike spiegel": "bebop",
        "hinata": "simp",
        "gintoki": "samurai",
        "izuku midoriya": "plus ultra",
        "bakugo": "explosion",
        "todoroki": "half cold half hot",
        "all might": "symbol of peace",
        "saitama": "one punch",
        "genos": "cyborg",
        "killua": "electricity",
        "leorio": "doctor",
        "kurapika": "chain",
        "hisoka": "magician",
        "yusuke": "spirit gun",
        "kuwabara": "spirit sword",
        "hiei": "dragon",
        "kurama": "fox",
        "toguro": "100 percent",
        "meruem": "ant king",
        "netero": "prayer",
        "jotaro": "star platinum",
        "sung jin woo": "shadow monarch",
        "giorno": "gold experience",
        "josuke": "crazy diamond",
        "rohan": "heaven's door",
        "kira yoshikage": "hand",
        "shinji": "eva unit 01",
        "rei": "clone",
        "asuka": "eva unit 02",
        "misato": "operations",
        "kenshin": "reverse blade",
        "sesshomaru": "demon lord",
        "inuyasha": "half demon",
        "kagome": "arrow",
        "natsu": "fire dragon",
        "gray": "ice make",
        "lucy": "celestial spirits",
        "jellal": "heavenly body",
        "kirito": "black swordsman",
        "asuna": "lightning flash",
        "kakashi": "mirror",
        "ryuk": "shinigami",
        "misa": "second kira",
        "near": "successor",
        "zoro": "three swords",
        "sanji": "black leg",
        "usopp": "sniper",
        "chopper": "doctor",
        "robin": "devil child",
        "mikasa": "ackerman",
        "armin": "colossal titan",
        "tanjiro": "water breathing",
        "nezuko": "demon",
        "zenitsu": "thunder breathing",
        "inosuke": "beast breathing",
        "giyu": "water hashira",
        "shinobu": "insect hashira",
        "nami": "navigator",
    },

    "soccer_players": {
        "messi": "goat",
        "ronaldo": "siuuu",
        "mbappe": "speed",
        "neymar": "brazil",
        "haaland": "machine",
        "salah": "egypt",
        "benzema": "balon dor",
        "modric": "croatia",
        "de bruyne": "assist king",
        "lewandowski": "poacher",
        "van dijk": "wall",
        "alisson": "liverpool",
        "ter stegen": "sweeper keeper",
        "oblak": "save percentage",
        "courtois": "real madrid",
        "kimmich": "versatile",
        "pedri": "barcelona",
        "gavi": "youngest",
        "yamal": "wonderkid",
        "vinicius junior": "dribbler",
        "bellingham": "england",
        "griezmann": "atletico",
        "osimhen": "napoli",
        "son heung-min": "korea",
        "kane": "no trophies",
        "rashford": "manchester",
        "saka": "arsenal",
        "foden": "city",
        "lautaro martinez": "inter",
        "dybala": "roma",
        "di maria": "winger",
        "ronaldinho": "freestyle",
        "rivaldo": "barcelona",
        "roberto carlos": "free kick",
        "zidane": "headbutt",
        "henry": "invincibles",
        "batistuta": "argentina",
        "tevez": "corinthians",
        "aguero": "93:20",
        "pulisic": "american",
        "dembele": "pace",
        "felix": "portugal",
        "nunez": "liverpool",
        "bruno fernandes": "penalties",
        "rice": "arsenal",
        "trippier": "newcastle",
    },

    "nba_players": {
        "lebron": "king",
        "curry": "three pointer",
        "jokic": "joker",
        "giannis": "greek freak",
        "durant": "slim reaper",
        "embiid": "the process",
        "kawhi": "the claw",
        "butler": "no days off",
        "lillard": "dame time",
        "tatum": "celtics",
        "brown": "boston",
        "mitchell": "spida",
        "booker": "suns",
        "westbrook": "triple double",
        "harden": "beard",
        "irving": "handles",
        "thompson": "splash brother",
        "green": "defense",
        "luka doncic": "maverick",
        "zion": "pelicans",
        "ingram": "tall",
        "trae young": "ice trae",
        "dejounte murray": "atlanta",
        "devin booker": "phoenix",
        "anthony davis": "brow",
        "jordan poole": "poole party",
        "pascal siakam": "toronto",
        "og anunoby": "raptors",
        "michael jordan": "six rings",
        "kobe bryant": "mamba",
        "shaquille oneal": "diesel",
        "magic johnson": "showtime",
        "larry bird": "legend",
        "charles barkley": "round mound",
        "hakeem olajuwon": "dream",
        "allen iverson": "practice",
        "dirk nowitzki": "german",
        "tim duncan": "big fundamental",
    },

    "brands": {
        "nike": "swoosh",
        "apple": "bitten",
        "ferrari": "prancing horse",
        "gucci": "double g",
        "rolex": "oyster",
        "adidas": "three stripes",
        "samsung": "galaxy",
        "sony": "playstation",
        "toyota": "reliable",
        "mercedes": "star",
        "bmw": "propeller",
        "porsche": "stuttgart",
        "lamborghini": "bull",
        "bentley": "wings",
        "rolls royce": "spirit",
        "bugatti": "chiron",
        "mclaren": "papaya",
        "louis vuitton": "monogram",
        "chanel": "number five",
        "hermes": "birkin",
        "prada": "triangle",
        "versace": "medusa",
        "balenciaga": "triple s",
        "coca cola": "red can",
        "pepsi": "globe",
        "mcdonalds": "arches",
        "starbucks": "siren",
        "red bull": "wings",
        "amazon": "arrow",
        "google": "multicolour",
        "microsoft": "windows",
        "meta": "infinity",
        "netflix": "red n",
        "spotify": "green",
        "tesla": "electric",
        "nvidia": "green eye",
        "lego": "brick",
        "nintendo": "mario",
        "ikea": "swedish",
        "zara": "fashion",
        "levis": "501",
        "ralph lauren": "polo pony",
        "converse": "all star",
        "vans": "checkerboard",
        "canon": "lens",
        "dyson": "cyclone",
        "heineken": "green bottle",
        "guinness": "dark",
        "jack daniels": "tennessee",
        "fedex": "hidden arrow",
        "uber": "surge pricing",
        "airbnb": "belo",
    },

    "adults_only": {
        "one night stand": "regret",
        "hangover": "sunday morning",
        "walk of shame": "yesterday's clothes",
        "tinder": "swipe right",
        "strip club": "dollar bills",
        "beer bong": "freshman",
        "body shots": "salt and lime",
        "skinny dipping": "midnight dare",
        "gangbang": "teamwork",
        "booty call": "2am text",
        "friends with benefits": "complicated",
        "open relationship": "boundaries",
        "morning after pill": "pharmacy run",
        "ghosting": "left on read",
        "situationship": "undefined",
        "sneaky link": "secret meetup",
        "rizz": "smooth talker",
        "thirst trap": "instagram",
        "simping": "no self respect",
        "netflix and chill": "who's watching",
        "drunk text": "instant regret",
        "lap dance": "ones",
        "sexting": "screenshots",
        "sugar daddy": "allowance",
        "only fans": "subscription",
        "blind date": "catfish risk",
        "speed dating": "three minutes",
        "divorce": "lawyers",
        "prenup": "just in case",
        "vasectomy": "snip",
        "pub crawl": "matching shirts",
        "bucks night": "last of freedom",
        "blowjob": "technique",
        "hangover cure": "greasy breakfast",
        "drunk munchies": "kebab",
        "anal": "exit",
        "walk in": "wrong timing",
        "threesome": "crowded",
        "cougar": "older woman",
        "sugar baby": "funded lifestyle",
    },
    # Uncomment below to use hardcoded hints instead of the API for these categories
    # "animals": {
    #     "penguin": "antarctica",
    #     "elephant": "trunk",
    #     "giraffe": "tall",
    #     "dolphin": "echolocation",
    #     "cheetah": "fastest",
    #     "gorilla": "silverback",
    #     "flamingo": "pink",
    #     "kangaroo": "pouch",
    #     "crocodile": "ancient",
    #     "chameleon": "colour change",
    #     "platypus": "venomous",
    #     "hamster": "wheel",
    #     "wolverine": "claws",
    #     "meerkat": "sentinel",
    #     "narwhal": "unicorn of sea",
    #     "axolotl": "regeneration",
    #     "capybara": "chill",
    #     "pangolin": "scales",
    #     "tapir": "snout",
    #     "okapi": "striped legs",
    #     "mandrill": "colourful face",
    #     "wombat": "cube poop",
    #     "echidna": "spines",
    #     "quokka": "happiest animal",
    #     "cassowary": "dangerous bird",
    #     "serval": "long legs",
    #     "caracal": "ear tufts",
    #     "ocelot": "spotted",
    #     "jaguar": "rosettes",
    #     "puma": "mountain lion",
    #     "lynx": "tufted ears",
    #     "bobcat": "short tail",
    #     "hyena": "laugh",
    #     "aardvark": "ant eater",
    #     "anteater": "long tongue",
    #     "armadillo": "armoured",
    #     "sloth": "slow",
    #     "manatee": "sea cow",
    #     "dugong": "mermaid legend",
    #     "walrus": "tusks",
    #     "sea lion": "balancing act",
    #     "harp seal": "white pup",
    #     "beluga whale": "canary of sea",
    #     "orca": "killer whale",
    #     "blue whale": "largest",
    #     "sperm whale": "deepest diver",
    #     "humpback whale": "songs",
    #     "manta ray": "wingspan",
    #     "hammerhead shark": "t shaped head",
    #     "great white shark": "jaws",
    #     "whale shark": "gentle giant",
    #     "octopus": "eight arms",
    #     "squid": "ink",
    #     "jellyfish": "no brain",
    #     "starfish": "regeneration",
    #     "sea turtle": "navigation",
    #     "iguana": "third eye",
    #     "komodo dragon": "venomous bite",
    #     "gecko": "sticky feet",
    #     "boa constrictor": "squeeze",
    #     "anaconda": "swamp",
    #     "king cobra": "hood",
    #     "rattlesnake": "warning rattle",
    #     "monitor lizard": "forked tongue",
    #     "salamander": "fire legend",
    #     "poison dart frog": "colourful warning",
    #     "toucan": "big beak",
    #     "macaw": "colourful parrot",
    #     "cockatoo": "crest",
    #     "peacock": "feathers",
    #     "ostrich": "fastest bird",
    #     "emu": "australia",
    #     "kiwi": "new zealand",
    #     "puffin": "clown of sea",
    #     "pelican": "pouch",
    #     "albatross": "wingspan",
    #     "condor": "vulture",
    #     "harpy eagle": "talons",
    #     "secretary bird": "stomping",
    #     "shoebill": "prehistoric",
    #     "red panda": "firefox",
    #     "giant panda": "bamboo",
    #     "sun bear": "smallest bear",
    #     "polar bear": "arctic",
    #     "grizzly bear": "salmon",
    #     "black bear": "forest",
    # },
 
    # "countries": {
    #     "brazil": "carnival",
    #     "japan": "cherry blossom",
    #     "kenya": "safari",
    #     "norway": "northern lights",
    #     "mexico": "tacos",
    #     "egypt": "pyramids",
    #     "india": "spices",
    #     "australia": "kangaroo",
    #     "argentina": "tango",
    #     "canada": "maple leaf",
    #     "france": "eiffel tower",
    #     "germany": "oktoberfest",
    #     "italy": "pasta",
    #     "spain": "flamenco",
    #     "portugal": "fado",
    #     "greece": "acropolis",
    #     "turkey": "bosphorus",
    #     "russia": "vodka",
    #     "china": "great wall",
    #     "south korea": "kpop",
    #     "vietnam": "pho",
    #     "thailand": "muay thai",
    #     "indonesia": "bali",
    #     "malaysia": "petronas",
    #     "philippines": "islands",
    #     "pakistan": "cricket",
    #     "bangladesh": "rivers",
    #     "iran": "persian",
    #     "iraq": "mesopotamia",
    #     "saudi arabia": "oil",
    #     "united arab emirates": "burj khalifa",
    #     "israel": "holy land",
    #     "jordan": "petra",
    #     "lebanon": "cedar",
    #     "morocco": "medina",
    #     "algeria": "sahara",
    #     "tunisia": "carthage",
    #     "ghana": "gold coast",
    #     "nigeria": "nollywood",
    #     "ethiopia": "coffee origin",
    #     "tanzania": "kilimanjaro",
    #     "south africa": "rainbow nation",
    #     "north korea": "hermit kingdom",
    #     "mozambique": "indian ocean",
    #     "angola": "oil rich",
    #     "cameroon": "indomitable lions",
    #     "senegal": "teranga",
    #     "ivory coast": "cocoa",
    #     "madagascar": "lemurs",
    #     "zambia": "victoria falls",
    #     "malawi": "warm heart",
    #     "peru": "machu picchu",
    #     "colombia": "coffee",
    #     "venezuela": "angel falls",
    #     "chile": "long and thin",
    #     "ecuador": "equator",
    #     "bolivia": "salt flats",
    #     "paraguay": "landlocked",
    #     "uruguay": "tiny",
    #     "cuba": "cigars",
    #     "jamaica": "reggae",
    #     "haiti": "first black republic",
    #     "dominican republic": "merengue",
    #     "costa rica": "pura vida",
    #     "panama": "canal",
    #     "guatemala": "maya",
    #     "honduras": "bay islands",
    #     "el salvador": "smallest",
    #     "nicaragua": "volcanoes",
    #     "niger": "sahel",
    #     "barbados": "rihanna",
    #     "bahamas": "paradise",
    #     "new zealand": "all blacks",
    #     "fiji": "islands",
    #     "papua new guinea": "tribes",
    #     "sweden": "ikea",
    #     "denmark": "lego",
    #     "finland": "sauna",
    #     "iceland": "geysers",
    #     "ireland": "shamrock",
    #     "poland": "pierogi",
    #     "czech republic": "beer",
    #     "slovakia": "mountains",
    #     "hungary": "goulash",
    #     "romania": "dracula",
    #     "bulgaria": "rose valley",
    #     "serbia": "belgrade",
    #     "croatia": "adriatic",
    #     "slovenia": "alpine",
    #     "bosnia": "sarajevo",
    #     "albania": "eagle",
    #     "ukraine": "sunflowers",
    #     "belarus": "landlocked",
    #     "georgia": "wine origin",
    #     "armenia": "mount ararat",
    #     "azerbaijan": "fire country",
    #     "kazakhstan": "steppe",
    # },
 
    # "sports": {
    #     "cricket": "wicket",
    #     "tennis": "love",
    #     "swimming": "lane",
    #     "gymnastics": "vault",
    #     "weightlifting": "snatch",
    #     "boxing": "uppercut",
    #     "wrestling": "pin",
    #     "judo": "mat",
    #     "taekwondo": "kick",
    #     "karate": "belt",
    #     "fencing": "touche",
    #     "archery": "bullseye",
    #     "rowing": "stroke",
    #     "canoeing": "paddle",
    #     "sailing": "tack",
    #     "cycling": "peloton",
    #     "triathlon": "transition",
    #     "marathon": "26 miles",
    #     "sprinting": "blocks",
    #     "hurdles": "clearance",
    #     "pole vault": "bar",
    #     "high jump": "fosbury flop",
    #     "long jump": "sand pit",
    #     "shot put": "heavy ball",
    #     "discus": "spin",
    #     "javelin": "spear",
    #     "biathlon": "rifle and skis",
    #     "alpine skiing": "slalom",
    #     "snowboarding": "halfpipe",
    #     "ice skating": "blades",
    #     "speed skating": "oval",
    #     "figure skating": "triple axel",
    #     "ice hockey": "puck",
    #     "curling": "broom",
    #     "bobsled": "track",
    #     "basketball": "dunk",
    #     "volleyball": "spike",
    #     "handball": "goal",
    #     "water polo": "cap",
    #     "diving": "pike",
    #     "surfing": "barrel",
    #     "skateboarding": "kickflip",
    #     "rock climbing": "belay",
    #     "baseball": "home run",
    #     "softball": "diamond",
    #     "american football": "touchdown",
    #     "rugby union": "scrum",
    #     "rugby league": "tackle",
    #     "lacrosse": "stick",
    #     "field hockey": "drag flick",
    #     "squash": "tin",
    #     "badminton": "shuttlecock",
    #     "table tennis": "ping pong",
    #     "snooker": "cue ball",
    #     "darts": "double top",
    #     "bowls": "jack",
    #     "netball": "goal shooter",
    #     "mixed martial arts": "octagon",
    #     "kickboxing": "roundhouse",
    #     "muay thai": "eight limbs",
    #     "sumo": "ring",
    # },
 
    # "school": {
    #     "calculator": "batteries",
    #     "textbook": "heavy bag",
    #     "detention": "punishment",
    #     "homework": "after school",
    #     "assembly": "microphone",
    #     "cafeteria": "lunch tray",
    #     "locker": "combination",
    #     "backpack": "straps",
    #     "pencil case": "zipper",
    #     "ruler": "thirty centimetres",
    #     "compass": "circle",
    #     "protractor": "angles",
    #     "whiteboard": "marker",
    #     "projector": "ceiling mounted",
    #     "gymnasium": "dodgeball",
    #     "library": "silence",
    #     "laboratory": "goggles",
    #     "classroom": "rows",
    #     "principal": "office",
    #     "teacher": "chalk",
    #     "substitute": "chaos",
    #     "counselor": "feelings",
    #     "janitor": "mop bucket",
    #     "librarian": "shushing",
    #     "exam": "pencil down",
    #     "report card": "parent signature",
    #     "semester": "half year",
    #     "excursion": "permission slip",
    #     "camp": "sleeping bag",
    #     "uniform": "tucked in",
    #     "timetable": "period one",
    #     "bell": "run",
    #     "recess": "playground",
    #     "lunch break": "oval",
    #     "roll call": "present",
    #     "history": "dates",
    #     "geography": "capitals",
    #     "mathematics": "equations",
    #     "biology": "dissection",
    #     "chemistry": "bunsen burner",
    #     "physics": "gravity",
    #     "english": "essay",
    #     "literature": "shakespeare",
    #     "art": "smock",
    #     "music": "recorder",
    #     "drama": "stage fright",
    #     "physical education": "running laps",
    #     "economics": "supply and demand",
    #     "suspension": "sent home",
    #     "expulsion": "permanent",
    #     "scholarship": "free ride",
    #     "graduation": "gown",
    #     "yearbook": "signatures",
    #     "school captain": "badge",
    #     "prefect": "responsibility",
    #     "valedictorian": "top student",
    #     "prom": "corsage",
    #     "science fair": "volcano",
    #     "sports day": "ribbon",
    #     "debating": "rebuttal",
    #     "chess club": "checkmate",
    #     "drama club": "audition",
    #     "canteen": "tuck shop",
    #     "oval": "grass",
    #     "basketball court": "free throw",
    #     "swimming pool": "chlorine",
    # },
 
    # "everyday_items": {
    #     "kettle": "boiling",
    #     "umbrella": "inside out",
    #     "pillow": "feathers",
    #     "toothbrush": "bristles",
    #     "alarm clock": "snooze",
    #     "wallet": "leather",
    #     "keys": "lost again",
    #     "charger": "low battery",
    #     "headphones": "tangled",
    #     "sunglasses": "uv protection",
    #     "water bottle": "hydration",
    #     "coffee mug": "monday morning",
    #     "remote control": "lost in couch",
    #     "doormat": "welcome",
    #     "laundry basket": "overflowing",
    #     "clothes hanger": "wire",
    #     "ironing board": "steam",
    #     "vacuum cleaner": "suction",
    #     "mop": "bucket",
    #     "broom": "sweeping",
    #     "dustpan": "brush",
    #     "garbage bin": "wheelie",
    #     "recycling bin": "yellow lid",
    #     "fridge": "leftovers",
    #     "microwave": "beeping",
    #     "toaster": "crumbs",
    #     "blender": "smoothie",
    #     "food processor": "chopping",
    #     "air fryer": "crispy",
    #     "washing machine": "spin cycle",
    #     "dryer": "lint trap",
    #     "dishwasher": "rinse aid",
    #     "oven": "preheating",
    #     "stovetop": "gas burner",
    #     "couch": "sunken cushions",
    #     "coffee table": "coasters",
    #     "bookshelf": "unread books",
    #     "desk lamp": "adjustable",
    #     "ceiling fan": "pull cord",
    #     "air conditioner": "remote",
    #     "heater": "dry air",
    #     "smoke alarm": "flat battery",
    #     "fire extinguisher": "red",
    #     "first aid kit": "bandaids",
    #     "toilet paper": "over or under",
    #     "soap dispenser": "pump",
    #     "tissue box": "last one",
    #     "mirror": "seven years",
    #     "bath mat": "damp",
    #     "shower curtain": "mould",
    #     "towel rack": "heated",
    #     "toilet brush": "behind toilet",
    #     "plunger": "emergency",
    #     "shampoo": "lather rinse repeat",
    #     "conditioner": "leave in",
    #     "razor": "five blades",
    #     "deodorant": "roll on",
    #     "moisturiser": "spf",
    #     "sunscreen": "reapply",
    #     "scissors": "dont run",
    #     "tape": "dispenser",
    #     "stapler": "jammed",
    #     "sticky note": "yellow",
    #     "envelope": "lick to seal",
    #     "pen": "clicked",
    #     "pencil": "sharpener",
    #     "highlighter": "fluorescent",
    #     "notebook": "spiral",
    #     "calendar": "wall",
    #     "photo frame": "mantelpiece",
    #     "vase": "flowers",
    # },
}


# Categories that use the Datamuse API for hints
API_CATEGORIES = {
    "animals": [
        "penguin", "elephant", "giraffe", "dolphin", "cheetah", "gorilla", "flamingo",
        "kangaroo", "crocodile", "chameleon", "platypus", "hamster", "wolverine", "meerkat",
        "narwhal", "axolotl", "capybara", "pangolin", "tapir", "okapi", "mandrill", "wombat",
        "echidna", "quokka", "cassowary", "serval", "caracal", "ocelot", "jaguar",
        "puma", "lynx", "bobcat", "hyena", "aardvark", "anteater", "armadillo", "sloth",
        "manatee", "dugong", "walrus", "sea lion", "harp seal", "beluga whale",
        "orca", "blue whale", "sperm whale", "humpback whale", "manta ray", "hammerhead shark",
        "great white shark", "whale shark", "octopus", "squid", "jellyfish", "starfish",
        "sea turtle", "iguana", "komodo dragon", "gecko", "boa constrictor", "anaconda",
        "king cobra", "rattlesnake", "monitor lizard", "salamander", "poison dart frog",
        "toucan", "macaw", "cockatoo", "peacock", "ostrich", "emu", "kiwi", "puffin",
        "pelican", "albatross", "condor", "harpy eagle", "secretary bird", "shoebill",
        "red panda", "giant panda", "sun bear", "polar bear", "grizzly bear", "black bear",
    ],

    "countries": [
        "brazil", "japan", "kenya", "norway", "mexico", "egypt", "india", "australia",
        "argentina", "canada", "france", "germany", "italy", "spain", "portugal", "greece",
        "turkey", "russia", "china", "south korea", "vietnam", "thailand", "indonesia",
        "malaysia", "philippines", "pakistan", "bangladesh", "iran", "iraq", "saudi arabia",
        "united arab emirates", "israel", "jordan", "lebanon", "morocco", "algeria", "tunisia",
        "ghana", "nigeria", "ethiopia", "tanzania", "south africa", "north korea", "mozambique",
        "angola", "cameroon", "senegal", "ivory coast", "madagascar", "zambia", "malawi",
        "peru", "colombia", "venezuela", "chile", "ecuador", "bolivia", "paraguay", "uruguay",
        "cuba", "jamaica", "haiti", "dominican republic", "costa rica", "panama", "guatemala",
        "honduras", "el salvador", "nicaragua", "niger", "barbados", "bahamas",
        "new zealand", "fiji", "papua new guinea", "sweden", "denmark", "finland",
        "iceland", "ireland", "poland", "czech republic", "slovakia", "hungary",
        "romania", "bulgaria", "serbia", "croatia", "slovenia", "bosnia", "albania",
        "ukraine", "belarus", "georgia", "armenia", "azerbaijan", "kazakhstan",
    ],

    "sports": [
        "cricket", "tennis", "swimming", "gymnastics", "weightlifting", "boxing",
        "wrestling", "judo", "taekwondo", "karate", "fencing", "archery",
        "rowing", "canoeing", "sailing", "cycling", "triathlon", "marathon",
        "sprinting", "hurdles", "pole vault", "high jump", "long jump", "shot put",
        "discus", "javelin", "biathlon", "alpine skiing", "snowboarding", "ice skating",
        "speed skating", "figure skating", "ice hockey", "curling", "bobsled",
        "basketball", "volleyball", "handball", "water polo", "diving", "surfing",
        "skateboarding", "rock climbing", "baseball", "softball", "american football",
        "rugby union", "rugby league", "lacrosse", "field hockey", "squash",
        "badminton", "table tennis", "snooker", "darts", "bowls", "netball",
        "mixed martial arts", "kickboxing", "muay thai", "sumo",
    ],

    "school": [
        "calculator", "textbook", "detention", "homework", "assembly", "cafeteria",
        "locker", "backpack", "pencil case", "ruler", "compass", "protractor",
        "whiteboard", "projector", "gymnasium", "library", "laboratory", "classroom",
        "principal", "teacher", "substitute", "counselor", "janitor", "librarian",
        "exam", "report card", "semester", "excursion", "camp", "uniform",
        "timetable", "bell", "recess", "lunch break", "roll call",
        "history", "geography", "mathematics", "biology", "chemistry", "physics",
        "english", "literature", "art", "music", "drama", "physical education",
        "economics", "detention", "suspension", "expulsion", "scholarship", "graduation",
        "yearbook", "school captain", "prefect", "valedictorian", "prom",
        "science fair", "sports day", "debating", "chess club", "drama club",
        "canteen", "oval", "basketball court", "swimming pool",
    ],

    "everyday_items": [
        "kettle", "umbrella", "pillow", "toothbrush", "alarm clock", "wallet",
        "keys", "charger", "headphones", "sunglasses", "water bottle", "coffee mug",
        "remote control", "doormat", "laundry basket", "clothes hanger", "ironing board",
        "vacuum cleaner", "mop", "broom", "dustpan", "garbage bin", "recycling bin",
        "fridge", "microwave", "toaster", "blender", "food processor", "air fryer",
        "washing machine", "dryer", "dishwasher", "oven", "stovetop",
        "couch", "coffee table", "bookshelf", "desk lamp", "ceiling fan", "air conditioner",
        "heater", "smoke alarm", "fire extinguisher", "first aid kit", "toilet paper",
        "soap dispenser", "tissue box", "mirror", "bath mat", "shower curtain",
        "towel rack", "toilet brush", "plunger", "shampoo", "conditioner",
        "razor", "deodorant", "moisturiser", "sunscreen", "scissors", "tape",
        "stapler", "sticky note", "envelope", "pen", "pencil", "highlighter",
        "notebook", "calendar", "photo frame", "vase",
    ],
}


def get_available_categories() -> list[str]:
    return list(PAIRED_CATEGORIES.keys()) + list(API_CATEGORIES.keys())